### ISSUE TITLE
ExtentMerge doesnt work properly when report is generated with custom config

### ISSUE THREAD

**Issue by ossa619** [anshooarora/extentreports#363] opened 2016-03-09 16:41 UTC
I generated some 4-5 reports with custom config from extent-config.xml. And when I try to merge them, it doesn't throw up error and the merged html file is also not getting generated.

**Comment by email2vimalraj** [comment] 2016-03-11 00:54
Share us your reports and extent-config.xml file to reproduce.

**Comment by ossa619** [comment] 2016-03-11 05:39
[extent-config.txt](https://github.com/anshooarora/extentreports/files/168506/extent-config.txt)
unable to upload .xml file so uploading it as .txt ....

**Comment by anshooarora** [comment] 2016-03-11 05:43
Most probably due to the custom date. This was supposed to be fixed in the next version of merge, but the tool is now deprecated in favor of ExtentX - which will do all this automatically. No manual merging required.

**Comment by ossa619** [comment] 2016-03-11 06:07
k fine ....

**Comment by ossa619** [comment] 2016-03-11 06:15
BTW ..... when will ExtentX be available .... :)

**Comment by email2vimalraj** [comment] 2016-03-11 10:39
ExtentX is already available (https://github.com/anshooarora/extentx). We are working on adding more features on it. You can hear a good news soon.

**Closed** 2016-03-11 12:53 UTC
