### ISSUE TITLE
support for the BDD frameworks such as Jbehave

### ISSUE THREAD

**Issue by igalep** [anshooarora/extentreports#17] opened 2015-07-12 06:39 UTC
Hi, 

It would be grate if you will also add a support for BDD testing frameworks such as Jbehave.

Thanks !

**Comment by anshooarora** [comment] 2015-07-13 17:41
Hello

ExtentReports support all sorts of test, BDD/TDD frameworks.  Its just like an API that you can make calls to create reports.  

If this does not answer your query, please provide more details.  What sort of behavior are you looking for to add support?

**Comment by anshooarora** [comment] 2015-07-14 03:45
Hello

Is this feature similar to #18?

**Comment by anshooarora** [comment] 2015-07-20 03:22
Closing this issue as its the exact duplicate of #18

**Closed by anshooarora** 2015-07-20 03:22 UTC

**Comment by nhtrmyfriends** [comment] 2016-10-27 09:52
HI,

can you povide the basic steps to include extentreports for JBehave.


Thanks 
Varun kumar
