### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by drormik** [anshooarora/extentreports#108] opened 2015-10-22 07:57 UTC
Hi some issues encountered with version 2.10

1.  this command fails:
report = new ExtentReports("C:\\report.html", true,DisplayOrder.OLDEST_FIRST, NetworkMode.OFFLINE );

Java says :
   "Exception in thread "main" java.lang.IllegalArgumentException: String input must not be null"

should i use something else to force the offline mode and display order ?

2.  setting the system info doesn't work.  the defaults are taken instead of  using the explicit values I've assigned with this command

		extent.addSystemInfo("Selenium Version", "2.46")
		.addSystemInfo("Environment", "Windows")	
		.addSystemInfo("Host Name", "ABC");

**Comment by anshooarora** [comment] 2015-10-22 15:42
The issue with OFFLINE reported earlier this week and fixed yesterday:  #103. 

I am unable to reproduce the 2nd issue.

**Comment by drormik** [comment] 2015-10-22 19:04
Perhaps this has to do with the  stage at which  the assignment takes place ? 
Is it before the "extent.startTest"   ?

could you provide a code excerpt from your test  ?

**Comment by karthikbhatnagar** [comment] 2015-10-23 01:20
dromik

Can you share I will see if I can reproduce.  I am adding my system info right after crating extent reports instance.

**Comment by anshooarora** [comment] 2015-10-27 19:45
Are you still having this issue?

I am able to use `addSystemInfo` anywhere in my run-session and it works.

**Comment by anshooarora** [comment] 2015-11-04 16:52
Closing ticket as there is no update.

**Closed** 2015-11-04 16:51 UTC
