### ISSUE TITLE
Graphic Bug on DashBoard

### ISSUE THREAD

**Issue by STBONNARD** [anshooarora/extentreports#365] opened 2016-03-10 17:08 UTC
Hello Anshoo arora

First, thank you a lot for your tool, it is very usefull :) on my testing project.

i noticed a strange graphic issue that randomly appears when running the Extenmerge command

when i merge 4 reports i get sometimes the issue, i am unable to understand the exact reason
maybe some actions on my scripts are missing 

Thank you in advance for your feedback.

Best Regards

Bonnard Stéphane
![capture du 2016-03-10 18 05 14](https://cloud.githubusercontent.com/assets/17768489/13677605/e978b02a-e6ea-11e5-879c-b327580ef575.png)

[Rapports.tar.gz](https://github.com/anshooarora/extentreports/files/167630/Rapports.tar.gz)
[ExtentMerge.html.tar.gz](https://github.com/anshooarora/extentreports/files/167631/ExtentMerge.html.tar.gz)

**Comment by anshooarora** [comment] 2016-03-10 21:00
Do you mean for the 2nd progress bar?

**Comment by STBONNARD** [comment] 2016-03-10 21:04
Yes exactly :)

as you can see sometimes one of the progress bar is empty, i noticed that one of the number of Test ( in this case it’s the number 2 , corresponding to the number of Failed runs i think) is shown
but hidden.

**Comment by anshooarora** [comment] 2016-03-10 21:05
In developer tools, I see that the percentage is used with a comma instead of a dot, which may be causing this..

![pregress](https://cloud.githubusercontent.com/assets/4107384/13684375/0411f960-e6d1-11e5-9b3b-03e12e6cf7cf.png)

**Comment by STBONNARD** [comment] 2016-03-10 21:20
Ok, but the calculation is maded by the ExtentMerge.jar? i didn’t modified anything on it
i’m not at the office right now so i’m unable to see if it’s my test scripts that could be involved in this behaviour, will tell you this tomorrow…

Thx for the analysis by the way :)

Best Regards

**Comment by email2vimalraj** [comment] 2016-03-11 00:53
I'm able to see the progress bar as expected with your reports properly:

![screen shot 2016-03-11 at 6 22 08 am](https://cloud.githubusercontent.com/assets/1214686/13689822/ca68c262-e751-11e5-81c6-14af26c5dc4f.png)

**Comment by email2vimalraj** [comment] 2016-03-11 00:55
I see you use Firefox, could you please share us the firefox version?

BTW, I tested this with firefox v43.0.1.

**Comment by STBONNARD** [comment] 2016-03-11 08:51
i'm using Firefox 42.0 into Linux Mint

**Comment by STBONNARD** [comment] 2016-03-11 08:52
i'm gonna try to update firefox asap

**Comment by STBONNARD** [comment] 2016-03-11 09:28
i do reproduce also with Chrome Version 47.0.2526.106 (64-bit)

still on linux Mint
![capture du 2016-03-11 10 28 40](https://cloud.githubusercontent.com/assets/17768489/13698392/0c14d530-e774-11e5-8823-63c505583500.png)

**Comment by STBONNARD** [comment] 2016-03-11 09:44
and the same on Firefox 44...
![capture du 2016-03-11 10 44 24](https://cloud.githubusercontent.com/assets/17768489/13698732/46418ed6-e776-11e5-8a4e-7134d635051e.png)

**Comment by STBONNARD** [comment] 2016-03-11 09:50
Indeed when i replace the comma by a dot on the percentage it works properly
but how did it come that on this particular calculation the value is setted with a comma?...
![dots](https://cloud.githubusercontent.com/assets/17768489/13698845/0081890e-e777-11e5-8340-47884ad55406.png)

**Comment by email2vimalraj** [comment] 2016-03-11 10:37
@STBONNARD: Did you try regenerating again and face the same problem?

**Comment by STBONNARD** [comment] 2016-03-11 10:40
This time the percentages values are setted without comma woth entire numbers
anyway i did reproduce randomly this issue, i will let you know if it happens again 

Thank you guys :)

![capture du 2016-03-11 11 39 18](https://cloud.githubusercontent.com/assets/17768489/13699934/f471b4a2-e77d-11e5-9784-b9fd2a7ff415.png)

**Comment by email2vimalraj** [comment] 2016-03-11 10:41
Good to hear the issue is resolved.

**Comment by STBONNARD** [comment] 2016-03-11 10:49
i do reproduce with another test launch...... :( same Browser Firefox 44
![capture du 2016-03-11 11 48 18](https://cloud.githubusercontent.com/assets/17768489/13700130/38b3048a-e77f-11e5-80c1-9ef83e403eb5.png)

**Comment by anshooarora** [comment] 2016-03-18 14:50
Issue comes from [here](https://github.com/anshooarora/extentreports/blob/master/extentmerge/src/main/java/com/relevantcodes/extentmerge/view/Template.ftl#L775).  Are you in a region where a `,` is used instead of `.` to separate decimal?

**Comment by STBONNARD** [comment] 2016-03-18 16:13
Hello Anshoo , thx for your reply, actually we are generating the report with your .jar we are based in France, so we might use fy default a comma i'm guessing...

do you have any idea on what to do about that

**Comment by anshooarora** [comment] 2016-03-18 17:12
You can recompile the sources, and replace the lines  [here](https://github.com/anshooarora/extentreports/blob/master/extentmerge/src/main/java/com/relevantcodes/extentmerge/view/Template.ftl#L775) to have `.` instead of `,`.

**Comment by STBONNARD** [comment] 2016-03-21 16:47
Ok i will try that and let you know the result

thx

**Comment by STBONNARD** [comment] 2016-03-24 10:47
do you have any further instructions on how resolving this problem exactly?

**Comment by STBONNARD** [comment] 2016-03-24 10:48
i don't know how to do the modification on the .jar

**Comment by anshooarora** [comment] 2016-06-15 12:52
@STBONNARD  -  Closing this as this product is no longer supported and ExtentX is the replacement.

**Closed by anshooarora** 2016-06-15 12:52 UTC
Labels: question
