### ISSUE TITLE
Issue with parent child relationship

### ISSUE THREAD

**Issue by rohitadvani** [anshooarora/extentreports#293] opened 2016-01-20 00:28 UTC
Hi Anshoo. I already raised this issue #254 but that issue seems to be closed already. I still have an issue in it and I added my comment in issue #254 itself. Would you be able to please visit that 254 closed ticket and refer to my comment.

I appreciate your kind help here.

Regards,
Rohit

**Comment by anshooarora** [comment] 2016-01-20 19:39
duplicate of #254

**Closed by anshooarora** 2016-01-20 19:39 UTC
Labels: duplicate
