### ISSUE TITLE
Layout issue while filtering by categories

### ISSUE THREAD

**Issue by MegaUkrainian** [anshooarora/extentreports#218] opened 2015-12-19 00:24 UTC
Hi,

It's hard to choose the category for filtering (see the screen)

STR:
1) Go to Test Details
2) Hover mouse on category label
![categories](https://cloud.githubusercontent.com/assets/13480390/11910037/a2f0268a-a5f7-11e5-99a6-7b85af9219de.jpg)

**Comment by anshooarora** [comment] 2015-12-19 00:33
What version?

**Comment by MegaUkrainian** [comment] 2015-12-19 01:16
Chrome 47.0.2526.106 Win7, Report 2.40, OfflineMode

**Comment by anshooarora** [comment] 2015-12-19 01:55
Tested on Chrome 47, Offline mode:

![img](https://cloud.githubusercontent.com/assets/4107384/11910637/0e9058e2-a5c1-11e5-84cc-7877c20ab5e4.png)

My result is with the latest alpha:   http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.40.1-alpha1.zip

But there were no changes to affect this portion of the UI so unsure what may be causing it..

**Comment by MegaUkrainian** [comment] 2015-12-19 02:14
It's observed only with enabled Developers toolbar. Version 2.40 (from maven repo).

**Comment by anshooarora** [comment] 2016-04-02 03:57
Are you still facing this issue with version 2.40.2?  I have done a few minor improvements for the upcoming version but this issue I was not able to reproduce on any supported browser..

**Comment by MegaUkrainian** [comment] 2016-04-02 08:42
The mentioned earlier issue is not observed.
However I found unneccessary scroll (see attachment)

![category](https://cloud.githubusercontent.com/assets/13480390/14225332/edaa6910-f8c7-11e5-9109-3ee1b48c5c7b.JPG)

**Comment by anshooarora** [comment] 2016-04-08 01:56
Can you add the below to your styles/css under extent-config.xml and see if it helps:

```
.dropdown-content { min-width: 300px !important; }
```

**Comment by MegaUkrainian** [comment] 2016-04-11 06:45
Yes, it works. However, tests drop-down list looks too long for its content.
![menu_023](https://cloud.githubusercontent.com/assets/13480390/14418806/f7159426-ffc9-11e5-82b2-0c1fffffd0bb.jpg)
If you have time, it would be great to make the drop-down adjustable according to the longest element.

**Comment by anshooarora** [comment] 2016-05-05 02:14
This is fixed in the most recent commit and will be available starting 2.41.0-beta4.  I am closing this for now, please reopen if you continue to encounter this issue.

**Closed by anshooarora** 2016-05-05 02:14 UTC
Labels: research
