### ISSUE TITLE
extentreports-net-v2.40.2 - System.NullReferenceException on EndTest and Close when run in parallel 

### ISSUE THREAD

**Issue by mittt** [anshooarora/extentreports#381] opened 2016-03-21 08:17 UTC
I'm getting NullReferenceExceptions on  EndTest and Close. It's happens rarely, I think it happens if most or all of my tests fail. Those are tests that are ran in parallel with NUnit 3. It was happening with the previous version also, but I didn't report it because I had to update to the latest one.

1) TearDown Error : WebTests.Tests.SetUpFixture
One or more child tests had errors
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at RelevantCodes.ExtentReports.Model.Report.<Terminate>b__53_0(ExtentTest x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RelevantCodes.ExtentReports.Model.Report.Terminate()
   at RelevantCodes.ExtentReports.ExtentReports.Close()
   at WebTests.Tests.SetUpFixtureBase.BaseRunAfterAnyTests() in d:\Program Files (x86)\Jenkins\jobs\Tests - OSM Web Tests in Android Chrome\workspace\SVN_OSMAutomaticTesting\SauceLabs_SeleniumProject\SetUpFixtureBase.cs:line 43
   at WebTests.Tests.SetUpFixtureBase.RunAfterAnyTests() in d:\Program Files (x86)\Jenkins\jobs\Tests - OSM Web Tests in Android Chrome\workspace\SVN_OSMAutomaticTesting\SauceLabs_SeleniumProject\SetUpFixtureBase.cs:line 57

2) Error : WebTests.Tests.RunTests(RMHub EBOKBC065374).BasicScenario
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at RelevantCodes.ExtentReports.ExtentReports.<>c.<RemoveChildTests>b__13_0(ExtentTest x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RelevantCodes.ExtentReports.ExtentReports.RemoveChildTests()
   at RelevantCodes.ExtentReports.ExtentReports.EndTest(ExtentTest Test)
   at WebTests.Tests.TestRunnerBase.TearDown() in d:\Program Files (x86)\Jenkins\jobs\Tests - OSM Web Tests in Android Chrome\workspace\SVN_OSMAutomaticTesting\SauceLabs_SeleniumProject\TestRunnerBase.cs:line 126

3) Error : WebTests.Tests.RunTests(RMHub EBOKBC065374).BasicScenatioIField
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at RelevantCodes.ExtentReports.ExtentReports.<>c.<RemoveChildTests>b__13_0(ExtentTest x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RelevantCodes.ExtentReports.ExtentReports.RemoveChildTests()
   at RelevantCodes.ExtentReports.ExtentReports.EndTest(ExtentTest Test)
   at WebTests.Tests.TestRunnerBase.TearDown() in d:\Program Files (x86)\Jenkins\jobs\Tests - OSM Web Tests in Android Chrome\workspace\SVN_OSMAutomaticTesting\SauceLabs_SeleniumProject\TestRunnerBase.cs:line 126

....... and followed by more like 3)

Best Regards!

**Comment by anshooarora** [comment] 2016-03-22 01:48
Support for parallel runs was added in 2.40.  If you can help me reproduce, I will release a fix.  Can you share what happens when a test fails, ie, steps that are used to report + end test?

**Comment by anshooarora** [comment] 2016-03-22 03:28
Is close being called multiple times?

**Comment by mittt** [comment] 2016-03-22 07:32
It's hard to reproduce because it happens rarely. 

Close on the report should have been called only once, else there is some bug with NUnit.
Also, EndTest() should have been called on all tests before Close().

**Comment by mittt** [comment] 2016-03-28 10:53
This happened again, today. 

Not sure if I can add any additional information. I'll look through all logs, again.

**Comment by mittt** [comment] 2016-03-28 12:06
Can't put my finger on it, but could it be related to the fact that you are locking on an object that you replace in the same block.

```
lock(TestList)
            { 
                TestList = TestList.Where(x => !x.GetTest().ChildNode).ToList();
            }
```
Also when you are adding to this collection you are not locking on anything, so what's added may get droped with this replace of the collection.


Same here, you should move this to the constructor:
```
  if (TestList == null)
            {
                TestList = new List<ExtentTest>();
            }
```

**Comment by anshooarora** [comment] 2016-03-29 04:10
Don't think the 1st one would cause an issue as the lock will only allow modification inside the block.  Will have to test with the 2nd one, or lock it as well so there are no clashes.

**Comment by anshooarora** [comment] 2016-04-12 18:20
Are you using child tests?

**Comment by mittt** [comment] 2016-04-12 18:24
No, I'm not.

**Comment by anshooarora** [comment] 2016-04-12 19:52
I think the issue was with `StartTest` accessing TestList without a lock.

**Comment by anshooarora** [comment] 2016-04-12 20:38
The fix is included in 2.41.0-b1, now available for download: extentreports.relevantcodes.com

**Comment by mittt** [comment] 2016-04-13 14:08
Ok, I have updated.

**Comment by mittt** [comment] 2016-04-18 06:32
It has not crashed, so far.

**Comment by anshooarora** [comment] 2016-05-06 17:35
@mittt - if this issue has popped up again, please let me know.. or if the issue can be closed?

**Comment by anshooarora** [comment] 2016-06-15 12:52
Closing ticket, looks like the issue was resolved with the previous build.

**Closed by anshooarora** 2016-06-15 12:52 UTC
Labels: bug
