### ISSUE TITLE
Updated with 2.41.0 jar of extent report instead of 2.40.1

### ISSUE THREAD

**Issue by sahiljindal1812** [anshooarora/extentreports#472] opened 2016-05-11 08:37 UTC
Still getting the same report which i was able to produce using 2.40.1 jar even after replacement with latest jar 2.41.0

When i mouse hover the dashboard graphs , it is not displaying the count specific to colors.
Can you please let me know where i am doing something wrong?

Thanks in Advance.

**Comment by sahiljindal1812** [comment] 2016-05-12 10:02
Can anyone help me in it.

**Comment by anshooarora** [comment] 2016-05-12 15:41
Please share your browser and OS types/versions.  I am unable to reproduce this behavior on any supported browsers.

See images below for mouse-over:

![pass](https://cloud.githubusercontent.com/assets/4107384/15220671/ebaa1518-182d-11e6-99e6-805fa56a03ee.png)
![error](https://cloud.githubusercontent.com/assets/4107384/15220672/ebb9d12e-182d-11e6-8661-51c0bf9dfb69.png)

**Comment by sahiljindal1812** [comment] 2016-05-13 10:28
Google Chrome : Version : 50.0.2661.94 m
Window OS :- 7

**Comment by anshooarora** [comment] 2016-06-15 12:59
Closing as this issue seems environment specific and isn't reproducible.

**Closed by anshooarora** 2016-06-15 12:59 UTC
Labels: question
