### ISSUE TITLE
Test View is showing incorrect result. Request to show the Test Case results and Test Steps results separately

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#64] opened 2015-08-25 06:12 UTC
Anshoo, 
Thanks for awesome application-agnostic reporting framework.
As per our discussion, i am logging this issue.

I have Test Case (Parent) and each test case has multiple test steps (childs)
While trying child test feature (program below), the test view graph is showing 6 steps failed and 1 step pass.
Where as we have total 6 steps only. Of which 5 fail and 1 pass.
So, showing 6 fail and 1 pass is incorrect. 

I request you to show the Test Case result and Test steps result separtely.
For the below program:
Test Cases: 1 FAIL
Test Steps: 5 FAIL, 1 PASS

Test Case result should be the summary of the actual child tests. ie. if all teststeps pass then testcase result pass, else even if one teststep FAIL/ ERROR then the test case result should be fail.

My Test program:
---------------
```
public class ExtentManagerTest {
    static private ExtentReports extent = ExtentManager.getInstance();
    static protected ExtentTest test;
    static ExtentTest parent = null;
    
    public static void main(String[] args) {
        // TODO Auto-generated method stub    
        parent = extent
                .startTest("Test Case1", "Test Case 1 has multiple test steps")
                .assignCategory("Category1");
        
        test2();
        test1();
        extent.endTest(parent);

        ExtentManager.closeInstance();
    }

    private static void test2() {
        // TODO Auto-generated method stub
        
        for (int i = 1; i < =5; i++){
            ExtentTest child2 = extent.startTest("Test Step: " + i);
            child2.log(LogStatus.FAIL, "FAIL");
            child2.log(LogStatus.INFO, "Information");
            
            parent        
            .appendChild(child2);
        }


    }

    private static void test1() {
        // TODO Auto-generated method stub        

        ExtentTest T1 = extent.startTest("TestStep: 6");
        T1.log(LogStatus.INFO, "Info");        

        parent
        .appendChild(T1);
    
    }
}
```
FYI, I am exploring 2.04 jar.

![advancedreport_testview_showing_incorrect_info](https://cloud.githubusercontent.com/assets/8359360/9459894/56038774-4b1e-11e5-8783-7e82b372deed.png)

**Comment by anshooarora** [comment] 2015-08-25 13:15
Madhusudhan - how does the following implementation look:

![childnodesview](https://cloud.githubusercontent.com/assets/4107384/9467444/6017b52c-4b01-11e5-83cd-2e6077c9fc5b.png)

Live sample <a href='http://relevantcodes.com/Tools/ExtentReports2/samples/ChildNodesView.html'>here</a>.

It uses a separate view for all tests and child nodes.

**Comment by mmau** [comment] 2015-08-26 06:15
Hi Anshoo, 

I am facing the counting number of test case are not correct in the following scenarios:

I have two test classes: DemoClass1 and DemoClass2. Each test class has three test cases: TestDemo1, TestDemo2, TestDemo3. I intentionally made one test case failed in each test class.
The total test cases failed should be two, but show as 4 because it counts the parent in each test class.

My Questions:
1. Is it possible if you can help fixing to not counting the parent? 
2. Is it possible to help fixing the "Total Time Taken" in Summary view correctly? 
3. If you design the parent/child for scenarios different with what I am testing, is it possible that you can add the feature of "Test Class/Test Case". The total time taken for Test Class should be the sum of all the time take to run for all test cases in that test class?

Thanks,
-mmau

![demosummarytestresults-extentreport](https://cloud.githubusercontent.com/assets/13894660/9486497/d51ae7e2-4b7c-11e5-9fdc-34d46b6ab4f6.png)
![demotestresults-extentreport](https://cloud.githubusercontent.com/assets/13894660/9486500/de6440be-4b7c-11e5-981f-e94a66f5ca93.png)

**Comment by anshooarora** [comment] 2015-08-26 06:26
#1 will be fixed in the upcoming release.

#2 - what issue are you having?  From what I see in the report, the total time taken is correct.

#3 - would a fix for #1 address this?

**Comment by anshooarora** [comment] 2015-08-26 14:19
Guys,  here is an updated sample:  http://relevantcodes.com/Tools/ExtentReports2/samples/ChildNodesView.html

Here is how the counting will work now:

All tests without child nodes - counted as 1
All child nodes - counted as 1
All parent nodes with child(ren) - counted as 0

So if you have the following structure

```
Test 1
Test 2
Test 3
  - Child 1
  - Child 2
Test 4 
  - Child 3
```

Total Count = 5 tests (Test 1, Test 2, Child 1, Child 2, Child 3)

**Comment by mmau** [comment] 2015-08-26 16:48
1 - will be fixed in the upcoming release.
Thanks a lot for fixing this. 
2 - what issue are you having? From what I see in the report, the total time taken is correct.
In my screenshots above, if I count the execution time of each test case in DemoClass1 is: 43s+27s+14s=84s. For DemoClass2: 35s+23s+12s=70s. 
If total execution of the Parent (DemoClass1) is counted, it should display as 84s instead of display the execution time of the first test case in that test class (43s). Same as DemoClass2.
The total Time Taken to run should be: Total run time of DemoClass1 (84s) + DemoClass2 (70s) = 164s (2m44s). In this case, it just displays: 1m19s.  
3 - would a fix for 1 address this?
Yes, it will fix what I need. The way you count total test in previous response is exactly what I am looking for.

**Comment by anshooarora** [comment] 2015-08-26 16:59
Please correct me if I am wrong, but shouldn't the difference be calculated between:

DemoClass1 Starting - 16:16:18
DemoClass2 Ending - 16:17:37

Looks like the child tests are all having the same ending time, doesn't look right to me.  This may be a bug, I will check.

**Comment by anshooarora** [comment] 2015-08-26 18:11
Ignore the last statement in my previous comment.  The child nodes will have the time ended when the appendChild method is used.  So all of them were probably added at the same time which is why the ending times are all same.

**Comment by mmau** [comment] 2015-08-26 20:31
Sorry, it was my bad. The reason is I did not call end for each test case. I sort the test case name and ended at the parent. That is why all the child ends at the same time.
I will try to find a way to end the child and be able to sort it so the test case name are listed in order.

**Comment by gsaimadhu** [comment] 2015-08-27 09:50
Thanks Anshoo for taking up this very quickly. I was looking for update in the feedback section. Today only i came across the comments here.

I looked into the url you shared:
http://relevantcodes.com/Tools/ExtentReports2/samples/ChildNodesView.html

I see there are 11 'Test Names'.
In Summary view, on LHS, The total steps shows as 13 passed. But,
In Details, when i 'filter tests' by PASS, then in summary view, on LHS, the total steps showing as 8 passed.  

i.e. there is a mismatch of passed tests in Quick Summary View (13 passed) and Details section view (8 passed). 
Similarly, there is a mismatch of fail tests in Quick Summary View (3 failed) and Details section view (2 failed). Seems 3 = 2 fail + 1 fatal ?

Please look into these.

Also, is there any way to display the count of total 'Test Names' ? ie. 11 in this example.

**Comment by karthikbhatnagar** [comment] 2015-08-27 11:23
Seems Anshoo has not yet implemented the filters section.  I counted manually and it matches the graph numbers

**Comment by anshooarora** [comment] 2015-08-27 14:14
That's right Madhu & Karthik.  Its expected behavior as of now because I need to implement the new filter logic to also include the child nodes.  Will share the new sample soon.

**Comment by gsaimadhu** [comment] 2015-08-27 15:56
OK Thanks Anshoo.

**Comment by anshooarora** [comment] 2015-08-28 13:50
Please check the same URL:  http://relevantcodes.com/Tools/ExtentReports2/samples/ChildNodesView.html

It has the correct logic for filters as well.  Let me know if you spot any other issues.

**Comment by gsaimadhu** [comment] 2015-08-29 06:30
Thanks Anshoo.
Most of the report looks fine.

I see there are 3 failures from Quick view. When i check i see only 2
failures as below:

Test with Nodes - Failure

**Comment by gsaimadhu** [comment] 2015-08-29 06:33
Thanks Anshoo.
Most of the report looks fine.

I see there are 3 failures from Quick view. When i check i see only 2
failures as below:

Test with Nodes - Failure: 1 FAIL (ie. child node 2)
Multiple Levels : 1 FAIL (ie. Level 3)

Am i missing any thing?

Also , in the view, the numbers for FATAL and UNKNOWN are not visible, can
you please update the coloring code to make the values visibile?

Thanks
Madhusudan G

**Comment by karthikbhatnagar** [comment] 2015-08-31 04:16
These also have count of fatal tests - 1 fatal + 2 fail.  Is that right Anshoo?

**Comment by anshooarora** [comment] 2015-08-31 14:52
Yes - the count is 3 because it also adds FATAL.  <a href='https://github.com/anshooarora/extentreports/blob/master/java/2.x/src/com/relevantcodes/extentreports/source/STANDARD.html#L887'>This</a> section shows the counting..

All steps other than FATAL, FAIL, PASS are included in Others.

**Comment by anshooarora** [comment] 2015-09-01 13:10
Guys,  here is the beta-2 of the upcoming version.  Has all the fixes we discussed in this thread:

http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.05-beta2.zip

**Comment by gsaimadhu** [comment] 2015-09-02 01:44
Anshoo,
I have tried this latest version. The results in graph are fine. But,
In Quick Summary:
The number of passed tests is always showing as 0, Even if there are child tests that are passed.

In mail, i sent my extent report.Please check it.
Example:
For Test Case Name: MA_R2_U1_TS4 | CREATE_CC_WITH_VALID_INFO | Create CC Configuration Settings with Valid Inputs
there are 3 child tests passed. 

Thanks
Madhusudan G

**Comment by anshooarora** [comment] 2015-09-02 03:10
Madhusudan - I did not receive the email..

**Comment by gsaimadhu** [comment] 2015-09-02 05:18
Anshoo,
I forwarded the mail. Please check and let me know if not received.

Thanks

**Comment by gsaimadhu** [comment] 2015-09-02 06:21
Another observation:
1. open extent report
Example: Test View shows 190 passed, 1 fail
2. Go to details section, select only fail.
3. Now click on Summary section/ link.

Actual Test View:
Showing 0 passed
1 failed.

Expected Test View:
190 passed, 1 fail

**Comment by anshooarora** [comment] 2015-09-02 17:00
This is because when you filter, the graphs will automatically change and show the counts of filters.  When you filter,  it will show you the counts of standalone-parent tests and child tests.

**Closed** 2015-09-02 17:48 UTC

**Comment by gsaimadhu** [comment] 2015-09-02 23:24
Can you please share the updated jar?

**Comment by AmitRai22** [comment] 2015-09-03 12:07
Hi Anshu,

Thanks for providing such a nice reporting framework .

Actually my automation project includes Selenium and JBehave(BDD) and I have implemented 
Extent 2.04   in my automation project (Selenium + Jbehave ).
Will it be  possible for  you add the information(Graph ,status ) for  all  Parent test cases?
Since  I am facing a problem with report .
Eg.There are  4  Parent Test cases  each has 0 or more child

So  I want ,
Total  Test case = {All Parent Test cases That is 4};
eg. 
Test 1
 Test 2
 Test 3
 •Child 3.1
 •Child 3.2
Test 4 
•Child 4.1



The above equation counts for Jbehave(BDD).

Because in JBehave,
There are Scenarios and each scenarios has step(s).
and I am treating Scenario(Testcase) as Parent  and  Step(Test step) as  Child 
So at the end ,
I want the information (Graph ,status etc)  of all the Scenarios executed(in this case Parent).

Could you please add  the graph and information for Parent test cases or can you change 
the first graph of Dashboardview  to the graph to show  information of all the Parent test cases?(if possible)
There is already a 'Step view'(as read in above comments)'. Can you please add 'Parent view'
Here Parent will have 0 or more child.

**Comment by anshooarora** [comment] 2015-09-03 20:08
Madhusudan - the updated jar can be found here:  http://relevantcodes.com/extentreports-for-selenium/  and you can view all the new features here:  http://extentreports.relevantcodes.com/2x/docs.html

**Comment by gsaimadhu** [comment] 2015-09-03 21:41
Thanks Anshoo.

**Comment by anuchitlangia** [comment] 2016-05-11 06:17
i am able to append the results of multiple TCs in one report.. but total test count is 1 and total steps is increased... i am using this report for my Coded UI framework.. Language used is c#...
is there any merge tool or method which i can consume to get one report for multiple test methods?
any suggestions?
![extentreport](https://cloud.githubusercontent.com/assets/19283249/15171659/e8cd47ae-176d-11e6-9fd1-b186a958d054.png)

**Comment by nhtrmyfriends** [comment] 2016-10-27 09:59
hi,

can you please explain how to include extentreports in jbehave


Thanks 
Varun
