### ISSUE TITLE
Unable to see categories on the Category Page

### ISSUE THREAD

**Issue by malavparekh** [anshooarora/extentreports#500] opened 2016-06-03 18:46 UTC
Extent Reports v2.41  downloaded on 2-Jun-16
these are the series of statements executed under different methods in the given order. However, it doesn't populate the Category section. 

static final ExtentReports extent = new ExtentReports("c:\\extent\\rep1.html",true,DisplayOrder.NEWEST_FIRST, NetworkMode.OFFLINE, Locale.ENGLISH);

ExtentTest test = extent.startTest(testContext.getName());

test.assignCategory("<Category name>");
test.log(LogStatus.INFO, "Log1");
test.log(LogStatus.Pass, "All Good");

extent.flush();
extent.close();

----------
as suggested by you, adding "extent.endTest(test);" after the test is over resolves the problem.

**Comment by anshooarora** [comment] 2016-06-03 19:12
Are you saying the issue is resolved with `endTest`?

**Closed** 2016-06-03 19:43 UTC
