### ISSUE TITLE
Java - extent reports: Can't add category in TestsNG

### ISSUE THREAD

**Issue by ebenda** [anshooarora/extentreports#38] opened 2015-08-02 12:23 UTC
Hi

I have two impl for extentreports testNG and Junit.
I have problem to use assignCategory in testNG while in junit this function work just fine.
Both imple are on version 2.03.

10x

Eyal

**Comment by anshooarora** [comment] 2015-08-03 00:57
Eyal

I would require more information.  Are you getting any errors, categories do not show up for tests?

**Comment by mohammedghouse36** [comment] 2015-09-21 08:35
Hi Anshoo,

I am using robotframework i,e by using java for automation mobile apps using appium tool. I am getting roboframework default results. But i want customized reports for that i used extent reports library i am getting reports i,e .html file but getting  last tescase displaying in the report. Can you plz help me on this.

**Comment by mohammedghouse36** [comment] 2015-09-21 09:04
Hi Anshoo,

I tried with junit it is showing last executed mehtod or test in report. I think this is bug in 2.0.5 verison. Please check once.

**Comment by mohammedghouse36** [comment] 2015-09-21 09:18
Hi Anshoo,

I attached both the sample codes. with java main method and with help of junit. Please help me on this. If i am incorrect please let me know how to correct.

![withjunit](https://cloud.githubusercontent.com/assets/8112554/9988616/b5440400-606f-11e5-9ab4-68a03d026a95.JPG)
![generaljavamain](https://cloud.githubusercontent.com/assets/8112554/9988620/bb732af4-606f-11e5-9c70-5e1d76603092.JPG)

**Comment by anshooarora** [comment] 2015-09-21 18:34
I would recommend ending tests in <code>@After</code> annotation, and using <code>flush()</code> there itself or in <code>@AfterClass</code.  Its not a bug, you will have to change.  

See here for example:  http://extentreports.relevantcodes.com/2x/docs.html#basic-junit-selenium-example

**Comment by anshooarora** [comment] 2015-10-06 17:12
I am closing this ticket as it is not an issue in Extent, requires user configuration to correctly display categories.

**Closed by anshooarora** 2015-10-06 17:12 UTC

**Comment by kunals4u** [comment] 2016-07-26 18:01
Hi Anshu, You are doing a great Job! I have been following your post since sometime now.

I am able to generate reports using ExtentReports+TestNG, but I don't to show/hide the Category in my Extent reports.html.Is this something possible? Thanks, Kunal

**Comment by mibhuiyan** [comment] 2016-09-27 14:45
Hello Ansu
 http://extentreports.relevantcodes.com/2x/docs.html#basic-junit-selenium-example
this url no more??
