### ISSUE TITLE
New feature request for Email-able report - User should be able to insert the Description message on the header and footer of the report

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#52] opened 2015-08-13 05:07 UTC
UAC
--------
1.User should have option to insert the Header message of the report ,By default description message should be displayed . if user want to insert their own message then they should be able to insert and default message should be removed .

2.User should have option to insert the Footer message of the report ,By default footermessage should be displayed . if user want to insert their own message then they should be able to insert and default message should be removed .

**Comment by anshooarora** [comment] 2015-08-13 15:56
Perwez, 

You can add a header message using:

```
extent.config().reportHeadline("Description message");
```

**Comment by perwez123** [comment] 2015-08-14 04:41
I tried this and it worked fine , But is it possible to insert the fonts style , size and Color ?

**Comment by anshooarora** [comment] 2016-03-18 14:25
Closing as duplicate of #51.

**Closed by anshooarora** 2016-03-18 14:25 UTC
