### ISSUE TITLE
Not support Chinese Characters

### ISSUE THREAD

**Issue by bernardwyt93** [anshooarora/extentreports#433] opened 2016-04-18 08:00 UTC
When i first run the test, chinese characters appear to be fine. 

![image](https://cloud.githubusercontent.com/assets/18526106/14597226/000f37d0-057e-11e6-84ca-8e86a47e5437.png)

But when i run the second time, the first test log chinese characters displayed like this.

![image](https://cloud.githubusercontent.com/assets/18526106/14597232/0cdcadd0-057e-11e6-8c93-bed4df7c2907.png)

My code is very simple
test.Log(LogStatus.Info, "易-支付宝");

Any advice on how i could manage this?

**Comment by anshooarora** [comment] 2016-04-18 12:36
2nd time with appending the 1st report?

**Comment by bernardwyt93** [comment] 2016-04-19 02:49
@anshooarora yes

**Comment by bernardwyt93** [comment] 2016-04-19 02:55
@anshooarora example

![image](https://cloud.githubusercontent.com/assets/18526106/14626339/f9684918-061c-11e6-88ed-e79b8ca486eb.png)

![image](https://cloud.githubusercontent.com/assets/18526106/14626345/06975886-061d-11e6-8d1e-f52c39dbdfb4.png)

The previous test Chinese characters distorted.

**Comment by anshooarora** [comment] 2016-04-19 02:58
Sometimes it is also because of your IDE settings?  Are you using Eclipse?  If yes, change the format to UTF-8 or the correct encoding and try again.  If it is not the IDE, you can also change the encoding in the extent config.XML.

**Comment by bernardwyt93** [comment] 2016-04-20 05:04
Im using .net and I've tried to use different encoding format - UTF-8, UTF-16 (in extent config.XML) which didn't work.
you can try to simulate the issue by entering “中文” when generating report.

**Comment by anshooarora** [comment] 2016-05-06 18:06
I am able to reproduce this when I overwrite the report.  Marking this as a bug.

**Comment by anshooarora** [comment] 2016-05-06 18:12
I have fixed this - turns out, we have to explicitly specify to retain the existing encoding in HTMLAgility.dll.  Fix will be released in the upcoming stable.

**Closed** 2016-05-10 23:47 UTC
Labels: bug
