### ISSUE TITLE
Error while initializing the Extent report

### ISSUE THREAD

**Issue by nareshks051** [anshooarora/extentreports#103] opened 2015-10-20 04:49 UTC
Hi Anshoo ,

I have downloaded the latest version of jars and i am getting the below exception while initializing the report .

java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:89)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:85)
	at java.util.Scanner.<init>(Scanner.java:619)
	at com.relevantcodes.extentreports.utils.Stream.toString(Stream.java:19)
	at com.relevantcodes.extentreports.utils.Resources.getText(Resources.java:21)
	at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:87)
	at com.relevantcodes.extentreports.Report.attach(Report.java:52)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:47)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:81)
	at Report2.main(Report2.java:82)
Exception in thread "main" java.lang.IllegalArgumentException: String input must not be null
	at org.jsoup.helper.Validate.notNull(Validate.java:26)
	at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:26)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:42)
	at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:53)
	at org.jsoup.parser.Parser.parse(Parser.java:89)
	at org.jsoup.Jsoup.parse(Jsoup.java:58)
	at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:88)
	at com.relevantcodes.extentreports.Report.attach(Report.java:52)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:47)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:81)
	at Report2.main(Report2.java:82)

Error is from this line in my code :

	static String reportLocation = "C:report2.html";  
	
		ExtentReports extent = new ExtentReports(reportLocation, true,NetworkMode.OFFLINE);

**Comment by virenv** [comment] 2015-10-20 10:24
static String reportLocation = "C:report2.html";  we are missing "\" in the path. Can you check this and see if the issue exists?

**Comment by nareshks051** [comment] 2015-10-21 01:52
Hi Anshoo ,

Report path is correctly given in code .My mistake while posting it here .

Path is :
static String reportLocation ="C:\\Workspace\\Demo\\ExtentReport\\report2.html"

Exception is occuring from the below method which is in

**Comment by anshooarora** [comment] 2015-10-21 02:10
This is a bug due to extra forward slash in the package path, and some users are having issues whereas others are not.  For example, I am unable to reproduce the bug with this path on my system. 

This will be fixed in 2.11.0 though, can you using ONLINE mode for now or download the package and rebuild the jar after correcting the path?

**Comment by nareshks051** [comment] 2015-10-21 02:35
Sure Anshoo Thanks for the suggestion

**Closed** 2015-10-21 20:49 UTC

**Comment by amolppatil92** [comment] 2016-03-08 09:57
can we configure extent report with jenkins?

thanks in advance.
