### ISSUE TITLE
Testng test method with Retry doesn't group test instead all retry test coming as separate test.

### ISSUE THREAD

**Issue by VinitSandesara** [anshooarora/extentreports#313] opened 2016-01-31 02:09 UTC
Hi Anshoo, for learning purpose i am using one of the extentReport example created by https://github.com/saikrishna321 which is in his github profile https://github.com/saikrishna321/extent_reports thru which it generates below extentReport, i wanna make some modification in report that groups “Retry” test in one group, for example in below screenshot i have shown “testApp” has 2 Retry so when i click on testApp it should have all it's retry like below

![screen shot 2016-01-30 at 8 09 31 pm](https://cloud.githubusercontent.com/assets/12589206/12699757/67f1f0f6-c78d-11e5-877d-3ed8e75175a9.png)

![screen shot 2016-01-30 at 7 52 02 pm](https://cloud.githubusercontent.com/assets/12589206/12699745/ea4e6440-c78c-11e5-933f-456024c70ce8.png)

Thanks
Vinit

**Comment by karthikbhatnagar** [comment] 2016-02-02 15:45
there is appendChild method, see this link: http://extentreports.relevantcodes.com/java/version2/docs.html#child-tests

**Comment by VinitSandesara** [comment] 2016-02-02 19:55
Thanks karthik for replying, using appendchild it works fine with parallel= classes but when i try using parallel=methods it messed up everything, sometime child test append in different parent test. If you have any working example with parallel=methods can you please share.

Thanks
Vinit

**Comment by karthikbhatnagar** [comment] 2016-02-03 05:40
My understanding is

Parallel class - entire class runs in 1 thread
Parallel method - all methods of class run in separate threads

Methods are more complicated to run, that's why most people RUn parallel classes but you can design in a way it can run parallel methods.

Docs already have example of parallel methods

http://extentreports.relevantcodes.com/java/version2/docs.html#parallel-runs

**Comment by anshooarora** [comment] 2016-03-18 14:44
Closing as duplicate of #106.  This is an enhancement, will be available soon.  The last status of a duplicate will be shown by default.

**Closed by anshooarora** 2016-03-18 14:44 UTC
