### ISSUE TITLE
Issue with Image in Report

### ISSUE THREAD

**Issue by dampfnudel** [anshooarora/extentreports#40] opened 2015-08-05 08:12 UTC
Hi,

If I am opening an image from the report then the lightbox does not work. It is not showing the resized image.
This problem happens to me in Chrome and Firefox (Safari is working fine). Can you please validate, if this happens also to you?

Regards

**Comment by anshooarora** [comment] 2015-08-05 13:33
I am unable to reproduce this in any browser..  I tried Chrome Firefox and IE.  

What version of Chrome and Firefox do you use?  I can try to reproduce on those.

**Comment by dampfnudel** [comment] 2015-08-05 14:09
Firefox 39.0
Chrome 44.0.2403.130

**Comment by anshooarora** [comment] 2015-08-05 14:13
I am using the same versions of the 2 browsers and lightbox is working fine..

![ff](https://cloud.githubusercontent.com/assets/4107384/9087744/1e74f7a6-3b52-11e5-9e08-d04dd51f64a7.png)
![chrome](https://cloud.githubusercontent.com/assets/4107384/9087746/2016add4-3b52-11e5-8113-ecab3c3a8e0b.png)

**Comment by dampfnudel** [comment] 2015-08-05 14:14
Seems to be a local issue. Thanks for checking.

**Comment by dampfnudel** [comment] 2015-08-05 14:17
It works also for me on your example pages. Just the new generated reports are not working. Maybe you can check the same.

**Comment by anshooarora** [comment] 2015-08-05 14:30
Would it be possible for me to view the report?  You can email me directly at:  anshooarora@gmail.com.  You can remove all the sensitive info and only send me the part that fails to work..

**Comment by anshooarora** [comment] 2015-08-06 03:29
Can you alsy try images in this link and see if they work?  I haven't been able to reproduce this but have made some changes in the most recent build that may help.

http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html

**Comment by dampfnudel** [comment] 2015-08-06 06:17
On the suggested page it is working. Maybe there is also a relation to child tests as I am trying to open the images from a child test.

**Comment by dampfnudel** [comment] 2015-08-06 06:24
Please find attached the code from Developer Tools.
<img width="731" alt="screen shot 2015-08-06 at 08 23 58" src="https://cloud.githubusercontent.com/assets/11321242/9105107/94830c68-3c14-11e5-9250-47c44a75a575.png">

**Comment by anshooarora** [comment] 2015-08-06 14:12
Tom - please try with the latest jar file:

http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.04beta.zip

I am unable to reproduce this still but please try with the latest as there are a lot of small improvements in the document.

**Comment by dampfnudel** [comment] 2015-08-07 07:21
The link is giving me a 404.

**Comment by anshooarora** [comment] 2015-08-07 12:32
Corrected the link. Please try again.

**Comment by dampfnudel** [comment] 2015-08-10 07:14
This version works!

**Comment by dampfnudel** [comment] 2015-08-10 08:04
Do you know when there will be a new maven version?

**Comment by anshooarora** [comment] 2015-08-25 19:28
Closing ticket as fix was included in 2.04.

**Closed by anshooarora** 2015-08-25 19:28 UTC
