### ISSUE TITLE
Need to have an emailable report

### ISSUE THREAD

**Issue by malavparekh** [anshooarora/extentreports#501] opened 2016-06-03 19:16 UTC
ExtentReports v2.41.

I have a feature request wherein I would like to produce a standalone emailable HTML report. 

My use case is that I'd like to add that HTML to an HTML email which will be sent automatically by Jenkins at the end of the testing job.

**Comment by Cooliinnnn** [comment] 2016-06-07 11:01
Very useful feature, would be great. Do you have it set up at the moment to send the TestNG emailable reports? Thats what my alternative is going to be for the moment.

**Comment by malavparekh** [comment] 2016-06-07 13:27
Yes @Cooliinnnn , I do have the TestNG emailable reports and already using that.

**Comment by anshooarora** [comment] 2016-06-14 13:59
This feature will be included in version 3 (java-8 only).  It will be vanilla HTML without charts/graphs as not all email clients support them.  

Closing this as this is duplicate of #51.

**Closed by anshooarora** 2016-06-14 13:59 UTC

**Comment by malavparekh** [comment] 2016-06-14 17:28
I have a suggestion on having the graphs / charts in emailable standalone reports.

It can contain the graphs as images (and not clickable graphs) that give an overall picture of the test results.

**Comment by anshooarora** [comment] 2016-06-14 18:14
Let me know if you know of a good toolkit to achieve this, besides Google charts, which due to its licensing will not be part of this project.

**Comment by bharathramaswamy** [comment] 2016-06-15 01:07
Hi all,

we can use the www.highcharts.com url for charts and graphs .

Thanks
Bharath Ramaswamy

On Tue, Jun 14, 2016 at 11:44 PM, Anshoo Arora <notifications@github.com>
wrote:

> Let me know if you know of a good toolkit to achieve this, besides Google
> charts, which due to its licensing will not be part of this project.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/501#issuecomment-225968401>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMLevQaqtAZy5g0kbwM5PSONULEycuSwks5qLu97gaJpZM4It05j>
> .
>



-- 
Bharath
